# Generated by Django 5.1.2 on 2024-12-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='date_sent',
            new_name='timestamp',
        ),
    ]
